# Default values for prometheus-mongodb-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ananthunair/mongodb_exporter
  tag: v1.0.0
  pullPolicy: IfNotPresent
replicas: 1
service:
  type: ClusterIP
  port: 9216
  targetPort: 9216

config:
  datasource: mongodb://localhost:27017

annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9216"
