apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "prometheus-mongodb-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-mongodb-exporter.name" . }}
    chart: {{ template "prometheus-mongodb-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "prometheus-mongodb-exporter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
      labels:
        app: {{ template "prometheus-mongodb-exporter.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: MONGODB_URL
              value: {{ .Values.config.datasource }}
              {{- if .Values.config.auth }}
            - name: HTTP_AUTH
              value: {{ .Values.config.auth }}
              {{- end}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP